# Generated by Django 4.1.3 on 2022-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=10)),
                ('b_content', models.CharField(max_length=2000)),
                ('b_date', models.DateTimeField(auto_now=True)),
                ('b_like', models.IntegerField(default=0)),
                ('b_comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content', models.CharField(max_length=50)),
            ],
        ),
    ]
